spring:     #多数据源
  thymeleaf:
    cache: false  # \u662F\u5426\u5F00\u542F\u7F13\u5B58\uFF0C\u9ED8\u8BA4true
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/   # \u524D\u7F00
    suffix: .html   # \u540E\u7F00
    check-template: true    # \u68C0\u67E5\u6A21\u677F\u662F\u5426\u5B58\u5728\uFF0C\u9ED8\u8BA4true
    check-template-location: true     #\u68C0\u67E5\u6A21\u677F\u4F4D\u7F6E\u662F\u5426\u5B58\u5728\uFF0C\u9ED8\u8BA4true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://localhost:3306/db_test?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
        username: root
        password: hc2919

      # 从库数据源slave
      slave:
        enabled: false
        url: jdbc:mysql://localhost:3306/db_test?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
        username: root
        password: hc2919
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      rewriteBatchedStatements: true
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      filters: stat,wall
      filter:
        wall:
          config:
            multi-statement-allow: true
            none-base-statement-allow: true
          enabled: true
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        #allow: 192.168.110.27 #127.0.0.1,192.168.163.1
        # IP黑名单 (存在共同时，deny优先于allow)
        #deny: 192.168.110.27 #192.168.1.73
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        #login-username: admin
        # 登录密码
        #login-password: 111111
  messages:
    basename: i18n.login
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml   # 所有 mapper 映射的文件所在目录位置 cn/peyton/children/chatter/
  type-aliases-package: cn.peyton.children.chatter.pojo